---
title: "p8105_hw5_amh2325"
author: "Amanda Howarth"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

#Load IRIS dataset from the TIDYVERSE 
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```
## PROBLEM 1
Write a function that takes a vector as an argument; replaces missing values using the rules defined above; and returns the resulting vector. Apply this function to the columns of iris_with_missing using a map statement. 

```{r}
iris_function1 = function(x) {
  if(!is.numeric(x))
    replace_na(x, "virginica")
  else if (is.numeric(x))
    replace_na(mean(x, na.rm = TRUE))
  }
```

CHECK FUNCTION 
```{r}

iris_function1(iris_with_missing$petal_width)

mean(iris_with_missing$petal_width, na.rm=TRUE)
```

```{r}
replace_iris = map(.x=iris_with_missing, ~iris_function1(.x))
replace_iris
```
